### ISSUE TITLE
Replace specific key avsc per type of record by generic key avsc

### ISSUE THREAD

**Issue by PHameete** [DRIVER-EU/avro-schemas#2]
Currently, all types of records (log, configuration, heartbeat, cap) have their own key avsc.

These schema's are all the same internally. Can we replace these schemas with a generic key schema? This is easier on the Java side where each avsc results in a unique class.

**Comment by PHameete** [comment]
Note: i've added a generic key schema in commit 5e341eb6ecdbc1f58feb358babe074d64b01ed63

**Comment by erikvullings** [comment]
Removed all the specific key schema's.
