### ISSUE TITLE
avro-schema-validator accepts invalid schemas

### ISSUE THREAD

**Issue by behrisch** [DRIVER-EU/avro-schemas#3]
an example is https://github.com/DRIVER-EU/python-test-bed-adapter/blob/3b871b2635175a55cb4bdc0ea24b4eb4ad309d4f/data/schemas/sumo/sumo_AffectedTraffic-value.avsc where the name field is missing for the inner type

**Comment by erikvullings** [comment]
The Kafka schema registry is more strict than the AVRO schema itself. According to the [schema specification](https://avro.apache.org/docs/current/spec.html), an array does not require a name.
